Repository fga-eps-mds/CollegeFlow, pull requests merged in 2022-09, with the labels that each got.

#162 [FEAT]: get subjects list from backend
  college_flow_app/lib/config/routes/flow_router.dart
  college_flow_app/lib/core/api_client.dart
  college_flow_app/lib/core/error_logger.dart
  college_flow_app/lib/core/exceptions.dart
  college_flow_app/lib/core/failures.dart
  college_flow_app/lib/core/service_locator_manager.dart
  college_flow_app/lib/features/list_subjects/domain/usecase/get_subjects_list.dart
  college_flow_app/lib/features/list_subjects/subject_injection_container.dart
  college_flow_app/lib/features/subject/data/datasources/subject_datasource.dart
  college_flow_app/lib/features/subject/data/models/subject_model.dart
  college_flow_app/lib/features/subject/data/models/subject_model.g.dart
  college_flow_app/lib/features/subject/data/repositories/subject_repository_impl.dart
  college_flow_app/lib/features/subject/domain/entities/subject.dart
  college_flow_app/lib/features/subject/domain/repositories/subject_repository.dart
  college_flow_app/lib/features/subject/domain/usecase/get_subjects_list.dart
  college_flow_app/lib/features/subject/infra/datasources/subject_datasource_impl.dart
  college_flow_app/lib/features/subject/infra/subjects_api_service.dart
  college_flow_app/lib/features/subject/infra/subjects_api_service.g.dart
  college_flow_app/lib/features/subject/mappers/subject_mapper.dart
  college_flow_app/lib/features/subject/presentation/bloc/filter_subject_list/filter_subject_list_bloc.dart
  college_flow_app/lib/features/subject/presentation/bloc/filter_subject_list/filter_subject_list_bloc.freezed.dart
  college_flow_app/lib/features/subject/presentation/bloc/filter_subject_list/filter_subject_list_event.dart
  college_flow_app/lib/features/subject/presentation/bloc/filter_subject_list/filter_subject_list_state.dart
  college_flow_app/lib/features/subject/presentation/bloc/load_subject_list/load_subject_list_bloc.dart
  college_flow_app/lib/features/subject/presentation/bloc/load_subject_list/load_subject_list_bloc.freezed.dart
  college_flow_app/lib/features/subject/presentation/bloc/load_subject_list/load_subject_list_event.dart
  college_flow_app/lib/features/subject/presentation/bloc/load_subject_list/load_subject_list_state.dart
  college_flow_app/lib/features/subject/presentation/list_subjects_page.dart
  college_flow_app/lib/features/subject/presentation/subjects_page.dart
  college_flow_app/lib/features/subject/subject_injection_container.dart
  college_flow_app/lib/features/subject/widgets/list_subjects_card.dart
  college_flow_app/lib/features/subject/widgets/searchbar.dart
  college_flow_app/lib/features/subject/widgets/subject_tile.dart
  college_flow_app/pubspec.lock
  college_flow_app/pubspec.yaml
Labels: type: enhancement, priority: high

#163 [FEAT]: add all unit tests to subject feature
  college_flow_app/lib/core/error_logger.dart
  college_flow_app/lib/core/failures.dart
  college_flow_app/lib/features/subject/data/datasources/subject_datasource.dart
  college_flow_app/lib/features/subject/data/mappers/subject_mapper.dart
  college_flow_app/lib/features/subject/data/repositories/subject_repository_impl.dart
  college_flow_app/lib/features/subject/domain/repositories/subject_repository.dart
  college_flow_app/lib/features/subject/domain/usecase/get_subjects_list.dart
  college_flow_app/lib/features/subject/infra/datasources/subject_datasource_impl.dart
  college_flow_app/lib/features/subject/infra/subjects_api_service.dart
  college_flow_app/lib/features/subject/infra/subjects_api_service.g.dart
  college_flow_app/pubspec.lock
  college_flow_app/pubspec.yaml
  college_flow_app/test/features/subject/data/repositories/subject_repository_impl_test.dart
  college_flow_app/test/features/subject/domain/usecases/get_subject_list_test.dart
  college_flow_app/test/features/subject/infra/datasources/subject_datasource_test.dart
  college_flow_app/test/features/subject/mocks/get_subjects_list_mock.dart
  college_flow_app/test/features/subject/mocks/subject_api_service_mock.dart
  college_flow_app/test/features/subject/mocks/subject_datasource_mock.dart
  college_flow_app/test/features/subject/mocks/subject_entity_factory.dart
  college_flow_app/test/features/subject/mocks/subject_model_factory.dart
  college_flow_app/test/features/subject/mocks/subject_repository_mock.dart
  college_flow_app/test/features/subject/presentation/blocs/filter_subject_list_bloc_test.dart
  college_flow_app/test/features/subject/presentation/blocs/load_subject_list_bloc_test.dart
Labels: type: enhancement, priority: medium

#165 [FEAT]: integrate events and create domain for review feature
  college_flow_app/lib/features/review/data/datasources/review_datasource.dart
  college_flow_app/lib/features/review/data/mappers/review_mapper.dart
  college_flow_app/lib/features/review/data/models/get_review_response_model.dart
  college_flow_app/lib/features/review/data/models/get_review_response_model.g.dart
  college_flow_app/lib/features/review/data/models/review_model.dart
  college_flow_app/lib/features/review/data/models/review_model.g.dart
  college_flow_app/lib/features/review/data/repositories/review_repository_impl.dart
  college_flow_app/lib/features/review/domain/entities/review.dart
  college_flow_app/lib/features/review/domain/repositories/review_repository.dart
  college_flow_app/lib/features/review/domain/usecases/get_review_lists.dart
  college_flow_app/lib/features/review/infra/api_service.dart
  college_flow_app/lib/features/review/infra/api_service.g.dart
  college_flow_app/lib/features/review/infra/datasources/review_datasource_impl.dart
  college_flow_app/lib/features/review/infra/review_api_service.dart
  college_flow_app/lib/features/review/infra/review_api_service.g.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_bloc.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_bloc.freezed.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_event.dart
  college_flow_app/lib/features/review/presentation/review_page.dart
  college_flow_app/lib/features/review/presentation/widgets/no_review_card.dart
  college_flow_app/lib/features/review/presentation/widgets/review_card.dart
  college_flow_app/lib/features/review/review_injection_container.dart
  college_flow_app/lib/features/subject/data/mappers/subject_mapper.dart
  college_flow_app/lib/features/subject/data/models/subject_model.dart
  college_flow_app/lib/features/subject/data/models/subject_model.g.dart
  college_flow_app/lib/features/subject/domain/entities/subject.dart
  college_flow_app/lib/features/subject/widgets/subject_tile.dart
  college_flow_app/test/features/review/data/repositories/review_repository_test.dart
  college_flow_app/test/features/review/domain/usecases/get_review_list_test.dart
  college_flow_app/test/features/review/infra/datasources/review_datasource_test.dart
  college_flow_app/test/features/review/mocks/get_review_list_mock.dart
  college_flow_app/test/features/review/mocks/get_review_response_model_factory.dart
  college_flow_app/test/features/review/mocks/review_api_service_mock.dart
  college_flow_app/test/features/review/mocks/review_datasource_mock.dart
  college_flow_app/test/features/review/mocks/review_entity_factory.dart
  college_flow_app/test/features/review/mocks/review_model_factory.dart
  college_flow_app/test/features/review/mocks/review_repository_mock.dart
  college_flow_app/test/features/review/presentation/blocs/load_review_list_bloc_test.dart
  college_flow_app/test/features/subject/mocks/subject_entity_factory.dart
  college_flow_app/test/features/subject/mocks/subject_model_factory.dart
  college_flow_app/test/widget_test.dart
Labels: type: enhancement

#166 [REFAC]: remove todos from code
  college_flow_app/lib/core/error_logger.dart
  college_flow_app/lib/core/service_locator_manager.dart
  college_flow_app/lib/features/review/data/models/review_model.dart
  college_flow_app/lib/features/review/data/repositories/review_repository_impl.dart
  college_flow_app/lib/features/review/presentation/widgets/textfields/flow_text_field.dart
  college_flow_app/lib/features/splash/presentation/widgets/walkthrough_base_page.dart
  college_flow_app/lib/shared/widgets/buttons/flow_button.dart
  college_flow_app/lib/shared/widgets/flow_icon.dart
  college_flow_app/lib/shared/widgets/flow_icon_button.dart
  college_flow_app/lib/shared/widgets/loading.dart
  college_flow_app/test/features/review/presentation/blocs/load_review_list_bloc_test.dart
  college_flow_app/test/features/subject/presentation/blocs/filter_subject_list_bloc_test.dart
  college_flow_app/test/features/subject/presentation/blocs/load_subject_list_bloc_test.dart
Labels: type: refac

#169 [FEAT]: review form flow
  college_flow_app/lib/config/routes/flow_router.dart
  college_flow_app/lib/features/review/data/datasources/review_datasource.dart
  college_flow_app/lib/features/review/data/mappers/review_mapper.dart
  college_flow_app/lib/features/review/data/repositories/review_repository_impl.dart
  college_flow_app/lib/features/review/domain/params/create_review_params.dart
  college_flow_app/lib/features/review/domain/repositories/review_repository.dart
  college_flow_app/lib/features/review/domain/usecases/create_review.dart
  college_flow_app/lib/features/review/infra/datasources/review_datasource_impl.dart
  college_flow_app/lib/features/review/infra/review_api_service.dart
  college_flow_app/lib/features/review/infra/review_api_service.g.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_bloc.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_bloc.freezed.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_event.dart
  college_flow_app/lib/features/review/presentation/cubit/create_review_cubit.dart
  college_flow_app/lib/features/review/presentation/cubit/create_review_cubit.freezed.dart
  college_flow_app/lib/features/review/presentation/cubit/create_review_state.dart
  college_flow_app/lib/features/review/presentation/review_form.dart
  college_flow_app/lib/features/review/presentation/review_form_page.dart
  college_flow_app/lib/features/review/presentation/review_list_page.dart
  college_flow_app/lib/features/review/presentation/widgets/header.dart
  college_flow_app/lib/features/review/presentation/widgets/textfields/description_text_field.dart
  college_flow_app/lib/features/review/presentation/widgets/textfields/flow_text_field.dart
  college_flow_app/lib/features/review/review_injection_container.dart
  college_flow_app/lib/features/splash/presentation/walkthrough_page.dart
  college_flow_app/lib/features/subject/presentation/subjects_page.dart
  college_flow_app/lib/features/subject/widgets/subject_tile.dart
  college_flow_app/lib/shared/widgets/flow_icon_button.dart
  college_flow_app/test/features/review/data/repositories/review_repository_test.dart
  college_flow_app/test/features/review/domain/usecases/create_review_test.dart
  college_flow_app/test/features/review/mocks/review_datasource_mock.dart
  college_flow_app/test/features/review/mocks/review_repository_mock.dart
Labels: type: enhancement

#170 [FEAT]: Integration test
  college_flow_app/integration_test/app_test.dart
  college_flow_app/ios/Flutter/Debug.xcconfig
  college_flow_app/ios/Flutter/Release.xcconfig
  college_flow_app/ios/Podfile
  college_flow_app/ios/Podfile.lock
  college_flow_app/ios/Runner.xcodeproj/project.pbxproj
  college_flow_app/ios/Runner.xcworkspace/contents.xcworkspacedata
  college_flow_app/lib/features/review/presentation/review_form_page.dart
  college_flow_app/lib/features/review/presentation/review_list_page.dart
  college_flow_app/lib/features/review/presentation/widgets/subject_card.dart
  college_flow_app/lib/features/splash/presentation/walkthrough_page.dart
  college_flow_app/lib/features/subject/presentation/subjects_page.dart
  college_flow_app/lib/features/subject/widgets/searchbar.dart
  college_flow_app/pubspec.lock
  college_flow_app/pubspec.yaml
Labels: type: enhancement

#171 [#160/REFAC]: Change in the project scope in the vision document
  vision_document.md
Labels: type: documentation, type: gh pages, type: refac

#173 [refac]: update readme
  README.md
Labels: type: documentation, priority: medium

#178 [docs]: add sprint 11 planning and update others sprints
  _sidebar.md
  img/gerenciamento/QuadroConhecimento/QuadroConhecimento11.png
  sprints/sprint_10.md
  sprints/sprint_11.md
  sprints/sprint_9.md
Labels: type: documentation, type: gh pages, priority: low

#180 [REFAC]: update tests
  college_flow_app/integration_test/app_test.dart
  college_flow_app/lib/features/review/domain/usecases/get_review_lists.dart
  college_flow_app/lib/features/review/presentation/widgets/confirmation_bottomsheet.dart
  college_flow_app/test/features/review/data/repositories/review_repository_test.dart
  college_flow_app/test/features/review/domain/usecases/get_review_list_test.dart
  college_flow_app/test/features/review/infra/datasources/review_datasource_test.dart
  college_flow_app/test/features/review/mocks/get_review_list_mock.dart
  college_flow_app/test/features/review/mocks/get_review_response_model_factory.dart
  college_flow_app/test/features/review/mocks/review_api_service_mock.dart
  college_flow_app/test/features/review/mocks/review_datasource_mock.dart
  college_flow_app/test/features/review/mocks/review_repository_mock.dart
  college_flow_app/test/features/review/mocks/review_response_factory.dart
  college_flow_app/test/features/review/presentation/blocs/load_review_list_bloc_test.dart
Labels: type: enhancement, type: refac

#182 refac: Add links to the GitHub profiles of the team members
  home.md
Labels: type: enhancement, type: gh pages

#179 Refac/rewrite diagrams
  architecture_document.md
  img/architecture/new-class-diagram.png
  img/architecture/new-usecases-diagram.png
Labels: type: documentation, type: gh pages

#185 Docs/last sprint
  README.md
  _sidebar.md
  architecture_document.md
  postmortem.md
  prototype.md
  sprints/sprint_1.md
  sprints/sprint_11.md
  sprints/sprint_2.md
Labels: type: documentation, type: gh pages, priority: low, status: needs information

#186 [refac]: update sidebar of github pages
  _sidebar.md
Labels: type: gh pages, priority: low
