Repository fga-eps-mds/CollegeFlow, pull requests merged in 2022-07, with the labels that each got.

#51 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report-issue-template.md
  .github/ISSUE_TEMPLATE/epic-issue-template.md
  .github/ISSUE_TEMPLATE/template-issue-de-feature.md
  .github/ISSUE_TEMPLATE/user-storie-issue-template.md
Labels: good first issue

#54 [FEAT] Vision Document
  vision_document.md
Labels: documentation, gh pages

#93 Add sprint 4 planing and add sprint 3 review
  img/gerenciamento/QuadroConhecimento4.jpeg
  img/gerenciamento/RetrospectivasSp3.png
  sprints/sprint_2.md
  sprints/sprint_3.md
  sprints/sprint_4.md
Labels: documentation

#95 [FEAT]: Medium fidelity prototype #49
  prototype.md
Labels: documentation, gh pages

#96 [#92/FEAT] Technical Viability Document
  architecture_techonologies.md
Labels: documentation, gh pages

#102 docs: Add sprint 5 planning and sprint 4 review and retrospective
  img/gerenciamento/QuadroConhecimento5.png
  img/gerenciamento/RetropectivaSp4.png
  sprints/sprint_4.md
  sprints/sprint_5.md
Labels: documentation

#105 [#53/REFAC] : Change in requirements
  vision_document.md
Labels: documentation, gh pages

#104 Feat/splash pages
  .vscode/launch.json
  college_flow_app/assets/fonts/OctinCollegeBk.ttf
  college_flow_app/assets/fonts/OctinCollegeHv.ttf
  college_flow_app/assets/fonts/OctinCollegeSb.ttf
  college_flow_app/assets/walkthrough01.png
  college_flow_app/assets/walkthrough02.png
  college_flow_app/assets/walkthrough03.png
  college_flow_app/lib/config/constants/assets_contants.dart
  college_flow_app/lib/config/design_system/data/colors/colors.dart
  college_flow_app/lib/config/design_system/data/spacing/spacing.dart
  college_flow_app/lib/config/routes/flow_router.dart
  college_flow_app/lib/config/themes/custom_theme.dart
  college_flow_app/lib/main.dart
  college_flow_app/lib/presentation/walkthrough/walkthrough_page.dart
  college_flow_app/lib/presentation/walkthrough/widgets/walkthrough_base_page.dart
  college_flow_app/lib/presentation/widgets/buttons/flow_button.dart
  college_flow_app/lib/presentation/widgets/gap.dart
  college_flow_app/pubspec.lock
  college_flow_app/pubspec.yaml
  docs/politica-de-git.md
  sprints/Sprint_Template/sprint-planing.md
  sprints/Sprint_Template/sprint-review.md
Labels: enhancement
