Repository fga-eps-mds/CollegeFlow, pull requests merged in 2022-08, with the labels that each got.

#111 refac: Refac register layout code
  college_flow_app/lib/config/themes/custom_theme.dart
  college_flow_app/lib/presentation/login/login_pages.dart
  college_flow_app/lib/presentation/register/admin/register_adm.dart
  college_flow_app/lib/presentation/register/register_geral.dart
  college_flow_app/lib/presentation/register/register_page.dart
  college_flow_app/lib/presentation/register/student/register_student.dart
  college_flow_app/lib/presentation/register/teacher/register_teacher.dart
  college_flow_app/lib/presentation/register/widgets/logo_bar.dart
  college_flow_app/lib/presentation/register/widgets/user_type_button.dart
  college_flow_app/lib/presentation/walkthrough/walkthrough_page.dart
  college_flow_app/lib/presentation/widgets/buttons/flow_button.dart
  college_flow_app/lib/presentation/widgets/gap.dart
Labels: bug

#126 [REFAC]: Remove unused informations from github pages
  indicators_metrics.md
Labels: type: refac

#125 [#53/REFAC]: Change in requirements
  vision_document.md
Labels: type: documentation, type: gh pages

#129 [REFAC]: arquitetura diagram
  architecture_document.md
  img/architecture/arch_backend_vision.png
  img/architecture/arch_frontend_vision.png
  img/architecture/arch_general_vision.png
  img/architecture/visao-backend.png
  img/architecture/visao-camada-apresentacao.png
  img/architecture/visao-geral.png
Labels: type: gh pages, type: refac

#128 [FEAT]: Usecase and class diagram
  architecture_document.md
  img/architecture/class_diagram.png
  img/architecture/usecases_diagram.png
Labels: type: gh pages

#127 Refac/refac readme
  .github/images/collegeflow-logo.png
  .github/images/logo-college-flow-background.png
  README.md
Labels: type: documentation, type: refac, priority: low

#139 rewrite: Rewrite last sprints
  sprints/sprint_1.md
  sprints/sprint_2.md
  sprints/sprint_3.md
  sprints/sprint_4.md
  sprints/sprint_5.md
  sprints/sprint_6.md
  sprints/sprint_7.md
  sprints/sprint_8.md
Labels: type: documentation, type: gh pages, priority: medium

#137 [FEAT]: Add figma icons
  college_flow_app/lib/config/design_system/data/icons/flow_icon_data.dart
  college_flow_app/lib/shared/widgets/flow_icon.dart
Labels: type: enhancement

#138 [FEAT} add colors ds tokens
  college_flow_app/lib/config/design_system/data/colors/colors.dart
  college_flow_app/lib/config/themes/custom_theme.dart
  college_flow_app/lib/features/splash/presentation/widgets/walkthrough_base_page.dart
  college_flow_app/lib/shared/widgets/buttons/flow_button.dart
  college_flow_app/lib/shared/widgets/checkboxlist.dart
  college_flow_app/lib/shared/widgets/checkboxlist_material.dart
  college_flow_app/lib/shared/widgets/flow_icon.dart
  college_flow_app/lib/shared/widgets/flow_icon_button.dart
  college_flow_app/lib/shared/widgets/textfield/flow_text_field.dart
Labels: type: enhancement, priority: low

#145 [Base]: Design System
  college_flow_app/lib/config/design_system/data/colors/colors.dart
  college_flow_app/lib/config/design_system/data/icons/flow_icon_data.dart
  college_flow_app/lib/config/themes/custom_theme.dart
  college_flow_app/lib/features/splash/presentation/widgets/walkthrough_base_page.dart
  college_flow_app/lib/shared/widgets/buttons/flow_button.dart
  college_flow_app/lib/shared/widgets/checkboxlist.dart
  college_flow_app/lib/shared/widgets/checkboxlist_material.dart
  college_flow_app/lib/shared/widgets/flow_icon.dart
  college_flow_app/lib/shared/widgets/flow_icon_button.dart
  college_flow_app/lib/shared/widgets/textfield/flow_text_field.dart
Labels: type: enhancement, priority: low

#144 Refac/remove dead code
  college_flow_app/lib/features/splash/presentation/walkthrough_page.dart
Labels: type: refac, priority: high

#152 Docs/sprint 9
  _sidebar.md
  img/gerenciamento/QuadroConhecimento/QuadroConhecimento8.png
  img/gerenciamento/QuadroConhecimento/QuadroConhecimento9.png
  img/gerenciamento/Retrospectiva/Retrospectiva08.png
  sprints/sprint_8.md
  sprints/sprint_9.md
Labels: type: documentation, type: gh pages, priority: medium

#146 [FEAT]: Review list UI
  college_flow_app/assets/icons/2.0x/admin_icon.png
  college_flow_app/assets/icons/2.0x/professor.png
  college_flow_app/assets/icons/2.0x/professor_icon.png
  college_flow_app/assets/icons/2.0x/student_icon.png
  college_flow_app/assets/icons/3.0x/admin_icon.png
  college_flow_app/assets/icons/3.0x/professor.png
  college_flow_app/assets/icons/3.0x/professor_icon.png
  college_flow_app/assets/icons/3.0x/student_icon.png
  college_flow_app/assets/icons/4.0x/admin_icon.png
  college_flow_app/assets/icons/4.0x/professor.png
  college_flow_app/assets/icons/4.0x/professor_icon.png
  college_flow_app/assets/icons/4.0x/student_icon.png
  college_flow_app/assets/icons/admin_icon.png
  college_flow_app/assets/icons/professor.png
  college_flow_app/assets/icons/professor_icon.png
  college_flow_app/assets/icons/student_icon.png
  college_flow_app/lib/config/design_system/data/icons/flow_icon_data.dart
  college_flow_app/lib/config/design_system/data/icons/gallery.dart
  college_flow_app/lib/config/routes/flow_router.dart
  college_flow_app/lib/config/routes/flow_routes.dart
  college_flow_app/lib/features/review/list_example.dart
  college_flow_app/lib/features/review/presentation/review_page.dart
  college_flow_app/lib/features/review/presentation/widgets/review_card.dart
  college_flow_app/lib/features/review/presentation/widgets/review_score_tag.dart
  college_flow_app/lib/features/review/presentation/widgets/subject_card.dart
  college_flow_app/lib/features/review/presentation/widgets/teacher_tag.dart
  college_flow_app/lib/features/splash/presentation/walkthrough_page.dart
  college_flow_app/lib/features/splash/presentation/widgets/walkthrough_base_page.dart
  college_flow_app/lib/shared/widgets/buttons/flow_button.dart
  college_flow_app/lib/shared/widgets/flow_icon.dart
  college_flow_app/lib/shared/widgets/flow_icon_button.dart
  college_flow_app/lib/shared/widgets/gap.dart
Labels: type: enhancement

#153 [FEAT] add bloc to review
  college_flow_app/lib/config/design_system/data/icons/flow_icon_data.dart
  college_flow_app/lib/core/exceptions.dart
  college_flow_app/lib/core/failures.dart
  college_flow_app/lib/core/service_locator_manager.dart
  college_flow_app/lib/features/review/domain/entities/review.dart
  college_flow_app/lib/features/review/domain/usecases/get_review_lists.dart
  college_flow_app/lib/features/review/infra/api_service.dart
  college_flow_app/lib/features/review/infra/api_service.g.dart
  college_flow_app/lib/features/review/list_example.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_bloc.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_bloc.freezed.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_event.dart
  college_flow_app/lib/features/review/presentation/bloc/load_review_list_state.dart
  college_flow_app/lib/features/review/presentation/review_page.dart
  college_flow_app/lib/features/review/presentation/widgets/review_card.dart
  college_flow_app/lib/features/review/review_injection_container.dart
  college_flow_app/lib/shared/base_page.dart
  college_flow_app/lib/shared/error_page.dart
  college_flow_app/lib/shared/loading_page.dart
  college_flow_app/lib/shared/widgets/flow_icon.dart
  college_flow_app/lib/shared/widgets/loading.dart
  college_flow_app/pubspec.lock
  college_flow_app/pubspec.yaml
Labels: type: enhancement, priority: medium

#155 [Feat]: Search subjects and others UI improvements
  college_flow_app/lib/core/service_locator_manager.dart
  college_flow_app/lib/features/list_subjects/domain/entities/subject.dart
  college_flow_app/lib/features/list_subjects/domain/usecase/get_subjects_list.dart
  college_flow_app/lib/features/list_subjects/presentation/bloc/filter_subject_list/filter_subject_list_bloc.dart
  college_flow_app/lib/features/list_subjects/presentation/bloc/filter_subject_list/filter_subject_list_bloc.freezed.dart
  college_flow_app/lib/features/list_subjects/presentation/bloc/filter_subject_list/filter_subject_list_event.dart
  college_flow_app/lib/features/list_subjects/presentation/bloc/filter_subject_list/filter_subject_list_state.dart
  college_flow_app/lib/features/list_subjects/presentation/bloc/load_subject_list/load_subject_list_bloc.dart
  college_flow_app/lib/features/list_subjects/presentation/bloc/load_subject_list/load_subject_list_bloc.freezed.dart
  college_flow_app/lib/features/list_subjects/presentation/bloc/load_subject_list/load_subject_list_event.dart
  college_flow_app/lib/features/list_subjects/presentation/bloc/load_subject_list/load_subject_list_state.dart
  college_flow_app/lib/features/list_subjects/presentation/list_subjects_page.dart
  college_flow_app/lib/features/list_subjects/presentation/subjects_page.dart
  college_flow_app/lib/features/list_subjects/subject_injection_container.dart
  college_flow_app/lib/features/list_subjects/widgets/list_subjects_card.dart
  college_flow_app/lib/features/list_subjects/widgets/searchbar.dart
  college_flow_app/lib/features/list_subjects/widgets/subject_tile.dart
  college_flow_app/lib/features/review/domain/usecases/get_review_lists.dart
  college_flow_app/lib/features/review/list_example.dart
  college_flow_app/lib/features/review/presentation/review_page.dart
  college_flow_app/lib/shared/widgets/header.dart
Labels: type: enhancement, priority: critical

#161 Docs/sprint 10
  _sidebar.md
  img/gerenciamento/QuadroConhecimento/QuadroConhecimento10.png
  img/gerenciamento/Retrospectiva/Retrospectiva09.png
  sprints/sprint_10.md
  sprints/sprint_9.md
Labels: type: gh pages
